---
title: "scratch"
author: "Keon Arbabi"
date: "19/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libraries 
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(tidytext)
  library(magrittr)
  library(here)
  library(data.table)
  library(lme4)
  library(MuMIn)
  library(GGally)
  library(cowplot)
  library(gridExtra)
  library(ggpubr)
  library(mice)
  library(stringr)
  library(svglite)
  library(performance)
  library(broom.mixed)
  library(dotwhisker)
})

font_size = 24

```

# functions 
```{r}
range01 = function(x){(x-min(x))/(max(x)-min(x))}

```

# human
## load data
```{r}
# load summarized ephys features 
ephys_h = read.csv(file = here("local","processed_ephys","human_ephys_features_berg.csv"))
# load microglia scores 
qcMetrics_h = read.csv(file = here("output","human_qcMetrics.csv")) %>% dplyr::select(c(sample_id, Microglia))
# load metadata
metadata_h = fread(file = here("data","patchseq","20200625_patchseq_metadata_human.csv"), data.table = FALSE) %>% 
  dplyr::rename(sample_id = transcriptomics_sample_id, cluster_label = corresponding_AIT2.3.1_alias) %>%
  mutate(cluster_label = factor(cluster_label,
                                levels = c("Exc L2 LAMP5 LTK","Exc L2-4 LINC00507 GLP2R","Exc L2-3 LINC00507 FREM3","Exc L3-4 RORB CARM1P1","Exc L3-5 RORB COL22A1"),
                                labels = c("LTK","GLP2R","FREM3","CARM1P1","COL22A1"))) %>%
  dplyr::select(c(ephys_session_id, sample_id, donor_id, cell_soma_normalized_depth, cluster_label)) %>%
  left_join(., qcMetrics_h, by = "sample_id") %>%
  left_join(., ephys_h, by = "ephys_session_id")

```

## linear models to compare microglia score with ephys features 
```{r}
# subset to samples with cell soma normalized depth and microglia scores 
metadata_h = metadata_h[!is.na(metadata_h$cell_soma_normalized_depth),]
metadata_h = metadata_h[!is.na(metadata_h$Microglia),]
# view features lacking enough data 
n_count = sapply(metadata_h, function(x) sum(!is.na(x))) %>% as.data.frame() %>% rownames_to_column(var = "feature")
# remove
metadata_h = metadata_h %>% dplyr::select(-c(slow_trough_v, slow_trough_t, adp_v, rheo_first_isi, adapt))

ephys_features = names(metadata_h)[7:ncol(metadata_h)]
meta_features = names(metadata_h)[1:6]
plot_lst = list()

# loop through ephys features 
for(f in ephys_features){
  # prepare data 
  lm_df = metadata_h[,c(meta_features,f)]
  lm_df = lm_df[complete.cases(lm_df),]
  names(lm_df)[ncol(lm_df)] = "feature"
  
  form = scale(feature) ~ 0 + cluster_label + scale(Microglia) + scale(cell_soma_normalized_depth) + (1|donor_id)
  tidy(lmer(form, data = lm_df, REML = FALSE)) %>%
    filter(effect == "fixed") %>%
    mutate(term = str_replace(term, "cluster_label", "")) %>%
    mutate(term = recode(term, `scale(Microglia)` = "Microglia", `scale(cell_soma_normalized_depth)` = "Normalized depth")) %>%
    dwplot +
    geom_vline(xintercept = 0, lty = 2) +
    scale_color_manual(values = "#114357") +
    labs(y = "Variable", x = "Std. Beta", title = paste0(f)) +
    theme_classic() +
    theme(legend.position = "none")
  
  ggsave(filename = paste0("./output/figures/ephys_norandom/",f,".jpeg"), width = 4.5, height = 5)
}

### No random effect of donor id 
# subset to samples with cell soma normalized depth and microglia scores 
metadata_h = metadata_h[!is.na(metadata_h$cell_soma_normalized_depth),]
metadata_h = metadata_h[!is.na(metadata_h$Microglia),]
# view features lacking enough data 
n_count = sapply(metadata_h, function(x) sum(!is.na(x))) %>% as.data.frame() %>% rownames_to_column(var = "feature")
# remove
metadata_h = metadata_h %>% dplyr::select(-c(slow_trough_v, slow_trough_t, adp_v, rheo_first_isi, adapt))

ephys_features = names(metadata_h)[7:ncol(metadata_h)]
meta_features = names(metadata_h)[1:6]
plot_lst = list()

# loop through ephys features 
for(f in ephys_features){
  # prepare data 
  lm_df = metadata_h[,c(meta_features,f)]
  lm_df = lm_df[complete.cases(lm_df),]
  names(lm_df)[ncol(lm_df)] = "feature"
  
  form = scale(feature) ~ 0 + cluster_label + scale(Microglia) + scale(cell_soma_normalized_depth) 
  tidy(lm(form, data = lm_df)) %>%
    mutate(term = str_replace(term, "cluster_label", "")) %>%
    mutate(term = recode(term, `scale(Microglia)` = "Microglia score", `scale(cell_soma_normalized_depth)` = "Normalized depth")) %>%
    dwplot +
    geom_vline(xintercept = 0, lty = 2) +
    scale_color_manual(values = "#114357") +
    labs(y = "Variable", x = "Std. Beta", title = paste0(f)) +
    theme_classic() +
    theme(legend.position = "none")
  
  ggsave(filename = paste0("./output/figures/ephys_norandom/",f,".jpeg"), width = 4.5, height = 5)
}

```





















